{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-offhours.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-offhours.labels" . | nindent 4 }}
{{- end }}
