apiVersion: v1
kind: Namespace
metadata:
  name: app-dev-argopp
  labels:
    offhours.platform.io/schedule: "dev"
  annotations:
    offhours.platform.io/argopp: "offhours-scenario-3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-api
  namespace: app-dev-argopp
  labels:
    name: smb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: smb-api
  template:
    metadata:
      labels:
        name: smb-api
    spec:
      containers:
        - name: api
          image: nginx:1.27
          ports:
            - containerPort: 80
