apiVersion: v1
kind: Namespace
metadata:
  name: app-dev-mixed
  labels:
    offhours.platform.io/schedule: "testing"
  annotations:
    offhours.platform.io/argoapp: "offhours-scenario-4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app-dev-mixed
  labels:
    name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  namespace: app-dev-mixed
  annotations:
    offhours.platform.io/protected: "true"
  labels:
    name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: processor
  template:
    metadata:
      labels:
        name: processor
    spec:
      containers:
        - name: processor
          image: busybox:1.36
          command: ["sh", "-c", "sleep 3600"]
