apiVersion: batch/v1
kind: CronJob
metadata:
  name: offhours-shutdown-qa-weekday
  namespace: offhours-system
spec:
  schedule: "*/4 * * * *"
  timeZone: "America/Sao_Paulo"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: offhours-sa
          restartPolicy: OnFailure
          containers:
            - name: offhours
              image: david210/k8s-offhours:0.2.3
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: offhours-config-qa-weekday
                - secretRef:
                    name: offhours-secrets
              env:
                - name: ACTION
                  value: shutdown
