apiVersion: v1
kind: ConfigMap
metadata:
  name: offhours-config
  namespace: offhours-system
data:
  SCHEDULE_NAME: "default"
  SCHEDULE_SCOPE: "namespace"
  ARGO_ENABLED: "false"
  VERBOSE: "true"
  DRY_RUN: "false"
  DEFAULT_STARTUP_REPLICAS: "1"
  PROTECTED_APP_STRICT_MODE: "true"
  ARGO_SCHEME: "https"
  ARGO_INSECURE: "true"
  ARGO_DISCOVERY_USE_AUTOMATIC: "true"
  ARGO_DISCOVERY_USE_MANUAL: "false"
  ARGO_API_RETRIES: "2"
  ARGO_API_RETRY_BASE_SECONDS: "0.2"
  ARGO_API_RETRY_MAX_SECONDS: "1.0"
---

# Lembrando que o nome do secret deve ser offhours-secrets, e as chaves ARGO_SERVER e ARGO_TOKEN são obrigatórias apenas quando ARGO_ENABLED=true
# Abaixo e so um exemplo de como criar o secret, evite expor informações sensíveis em arquivos de configuração por questões de segurança.
apiVersion: v1
kind: Secret
metadata:
  name: offhours-secrets
  namespace: offhours-system
type: Opaque
stringData:
  # Obrigatorio apenas quando ARGO_ENABLED=true
  ARGO_SERVER: ""
  ARGO_TOKEN: ""
